### PR TITLE
Add PyFuture.__repr__ and PyTask.__repr__

### PR DESCRIPTION
**Pull request by messense**
Ref #20 

Really just a naive implementation, a lot more could be added to be more like asyncio's.

https://github.com/python/cpython/blob/master/Lib/asyncio/base_futures.py#L54
https://github.com/python/cpython/blob/master/Lib/asyncio/base_tasks.py#L8

### CODE REVIEW

**Comment by fafhrd91** [comment]
this is good starting point. eventually we need to pass with test https://github.com/PyO3/tokio/blob/master/tests/test_futures.py#L129

**Comment by messense** [comment]
It's actually more complicated than I think when callbacks and exception tracebacks needs to be added.

**Comment by messense** [comment]
`uvloop` simply inherits from asyncio's `Future` to provide `__repr__` implementation.

https://github.com/MagicStack/uvloop/blob/master/uvloop/future.pyx#L469

**Comment by fafhrd91** [comment]
try to call `Future.__repr__` with pyfuture self as self, it may work

**Comment by messense** [comment]
```python
In [1]: import asyncio

In [2]: import tokio

In [3]: loop = tokio.new_event_loop()

In [4]: tokio_fut = loop.create_future()

In [5]: asyncio.Future.__repr__(tokio_fut)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-3464b41f0865> in <module>()
----> 1 asyncio.Future.__repr__(tokio_fut)

TypeError: descriptor '__repr__' requires a '_asyncio.Future' object but received a 'tokio.PyFuture'
```

**Comment by fafhrd91** [comment]
ok, lets leave this ticket for right now

**Comment by messense** [comment]
Maybe get subclassing support in `rust-cpython` would work.

**Comment by fafhrd91** [comment]
eventually, it is low priority right now

**Pull request closed without merging**
